services:
  neo4j-propagation-metagraph:
    image: neo4j:latest
    container_name: neo4j-propagation-metagraph
    ports:
      - "${PROPAGATED_METAGRAPH_DESKTOP_PORT}:7474"
      - "${PROPAGATED_METAGRAPH_BOLT_PORT}:7687"
    volumes:
      - ${PROPAGATED_METAGRAPH_DIR}/data:/data
      - ${PROPAGATED_METAGRAPH_DIR}/logs:/logs
      - ${PROPAGATED_METAGRAPH_DIR}/conf:/conf
      - ${PROPAGATED_METAGRAPH_DIR}/import:/import
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc"]
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
