services:
  neo4j-mapped-graph:
    image: neo4j:latest
    container_name: neo4j-mapped-graph
    ports:
      - "${MAPPED_GRAPH_DESKTOP_PORT}:7474"
      - "${MAPPED_GRAPH_BOLT_PORT}:7687"
    volumes:
      - ${MAPPED_GRAPH_DIR}/data:/data
      - ${MAPPED_GRAPH_DIR}/logs:/logs
      - ${MAPPED_GRAPH_DIR}/conf:/conf
      - ${MAPPED_GRAPH_DIR}/import:/import
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc"]
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
