services:
  neo4j-metagraph:
    image: neo4j:latest
    container_name: filtered_knowledge_graph
    ports:
      - "7478:7474"
      - "7691:7687"
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./conf:/conf
      - ./import:/import
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc"]
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
