services:
  filtered_rolledup_graph:
    image: neo4j:latest
    container_name: filtered_rolledup_graph
    user: "7474:7474"
    ports:
      - "7477:7474"
      - "7690:7687"
    volumes:
      - ~/mnt/client_data/mikrobiome_kg/s4_filtered_rolledup_graph/data:/data
      - ~/mnt/client_data/mikrobiome_kg/s4_filtered_rolledup_graph/logs:/logs
      - ~/mnt/client_data/mikrobiome_kg/s4_filtered_rolledup_graph/conf:/conf
      - ~/mnt/client_data/mikrobiome_kg/s4_filtered_rolledup_graph/import:/import
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_memory_heap_initial__size=20G
      - NEO4J_server_memory_heap_max__size=20G
      - NEO4J_server_memory_pagecache_size=14G
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

